spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/odata_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: odata-demo
server:
  port: 8080
odata:
  path: /odata
logging:
  level:
    com.jinyi.odatademo: DEBUG
